# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d4d00fac759b879ff6953946feb4fca77a42d77a7ab298b9485c2b15e67bfa7829f4c6e97192bc16ee1eb5b09bf6bad6be1b7d860b4279b04d81976afd59c59

test:
  secret_key_base: c60077417d7df22a6ee4bce340ae2541110ff2668310836063df7a5238b59769b9ab9246d0c3255e778185feb635fd896f08fb52ef4c7b982ed37dea84c9cde6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
